name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Auto-upgrade any @capacitor/* packages to v7 to match @capacitor/core@7
      - name: Align Capacitor plugins to v7
        run: |
          node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json','utf8'));const bump=o=>{if(!o)return;for(const k of Object.keys(o)){if(k.startsWith('@capacitor/')){const v=o[k];if(!/^\^?7\./.test(v)) o[k]='^7.0.0';}}};bump(p.dependencies);bump(p.devDependencies);fs.writeFileSync('package.json',JSON.stringify(p,null,2));"
          rm -f package-lock.json
          npm i --no-audit --no-fund

      - name: Build web assets
        run: npm run build

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Ensure Android platform
        run: npx cap add android || true

      - name: Sync Capacitor (plugins & native)
        run: npx cap sync android

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
