name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Upgrade any @capacitor/* packages to v7 to match @capacitor/core@7
      - name: Align Capacitor packages to v7
        shell: bash
        run: |
          PKGS=$(node -e 'const p=require("./package.json"); const names=[...Object.keys(p.dependencies||{}), ...Object.keys(p.devDependencies||{})].filter(n=>n.startsWith("@capacitor/")).map(n=>`${n}@^7`); console.log(names.join(" "));')
          echo "Upgrading: $PKGS"
          rm -f package-lock.json
          if [ -n "$PKGS" ]; then
            npm i $PKGS --no-audit --no-fund
          fi
          npm i --no-audit --no-fund

      - name: Build web assets
        run: npm run build

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Ensure Android platform
        run: npx cap add android || true

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
