name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Align all @capacitor/* packages to v7 to match @capacitor/core@7
      - name: Align Capacitor packages to v7
        shell: bash
        run: |
          PKGS=$(node - <<'NODE'
          const p=require("./package.json");
          const all={...(p.dependencies||{}), ...(p.devDependencies||{})};
          const names=Object.keys(all).filter(n=>n.startsWith("@capacitor/")).map(n=>n+"@^7");
          process.stdout.write(names.join(" "));
          NODE
          )
          echo "Upgrading: $PKGS"
          rm -f package-lock.json
          if [ -n "$PKGS" ]; then
            npm i $PKGS --no-audit --no-fund
          fi
          npm i --no-audit --no-fund

      - name: Build web assets
        run: npm run build

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # ✅ Replace broken capacitor.config.ts with a valid Capacitor 7 config
      - name: Write clean Capacitor config
        shell: bash
        run: |
          if [ -f capacitor.config.ts ]; then mv capacitor.config.ts capacitor.config.ts.bak || true; fi
          cat > capacitor.config.ts <<'EOF'
          import type { CapacitorConfig } from '@capacitor/cli';

          const config: CapacitorConfig = {
            appId: 'com.memorystreamer.app',           // reverse-DNS, no dashes
            appName: 'Memory Streamer',
            webDir: 'dist',                            // Vite build output
            server: {
              androidScheme: 'https'
            }
          };

          export default config;
          EOF
          echo "Wrote fresh capacitor.config.ts"

      - name: Ensure Android platform
        run: npx cap add android || true

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
