name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Helper script to bump all @capacitor/* deps to ^7
      - name: Write fix-cap-versions.cjs
        run: |
          cat > fix-cap-versions.cjs <<'EOF'
          const fs = require('fs');
          const pkgPath = 'package.json';
          const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
          const bump = (obj) => {
            if (!obj) return;
            for (const name of Object.keys(obj)) {
              if (name.startsWith('@capacitor/')) obj[name] = '^7.0.0';
            }
          };
          bump(pkg.dependencies);
          bump(pkg.devDependencies);
          fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
          console.log('Updated @capacitor/* to ^7.0.0');
          EOF

      - name: Align Capacitor packages to v7
        run: |
          node fix-cap-versions.cjs
          rm -f package-lock.json
          npm i --no-audit --no-fund

      - name: Build web assets
        run: npm run build

      # Use JDK 21 to match AGP/--release 21
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      # Write a clean Capacitor v7 config (valid appId + typical Vite webDir)
      - name: Write clean capacitor.config.ts
        run: |
          cat > capacitor.config.ts <<'EOF'
          import type { CapacitorConfig } from '@capacitor/cli';

          const config: CapacitorConfig = {
            appId: 'com.memorystreamer.app',   // reverse-DNS, no dashes
            appName: 'Memory Streamer',
            webDir: 'dist',
            server: { androidScheme: 'https' }
          };

          export default config;
          EOF

      - name: Ensure Android platform
        run: npx cap add android || true

      - name: Sync Capacitor (plugins & native)
        run: npx cap sync android

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
